Repository osamhack2021/AI_WEB_POOL_YD, pull requests merged in 2021-10, with the labels that each got.

#14 `explicit-module-boundary-types` 타입스크립트 ESLint 규칙 조건 무시
  Web/.eslintrc.js
Labels: setting

#15 네비바 계정 메뉴에 "회원가입" 버튼 추가
  Web/src/App.vue
  Web/src/components/app/AppNonLoginAccountMenu.vue
Labels: feature

#17 피드에 기본적인? 글 작성 폼 추가
  Web/src/components/feed/FeedCompose.vue
  Web/src/components/feed/FeedItem.vue
  Web/src/pages/feed/MainFeedPage.vue
Labels: feature

#18 린트 오류 수정
  Web/src/pages/account/MyPage.vue
  Web/src/pages/account/MyPageRecords.vue
Labels: bug, refactor

#20 Node.js 의존성 패키지 업데이트
  Web/package.json
  Web/yarn.lock
Labels: setting

#21 약간의 스타일링
  Web/src/App.vue
  Web/src/components/app/AppTabNavigation.vue
  Web/src/pages/feed/MainFeedPage.vue
  Web/src/router/index.ts
Labels: styling

#24 피드 아이템에서 `... times ago`에 마우스 호버링 시 전체 업로드 일자 문자열 표시
  Web/src/components/feed/FeedItem.vue
Labels: feature, quick

#25 포스트(글) 페이지 기본 구현
  Web/src/components/feed/FeedCompose.vue
  Web/src/components/feed/FeedItem.vue
  Web/src/interfaces/IDatabaseData.ts
  Web/src/pages/article/ArticleViewPage.vue
  Web/src/pages/feed/MainFeedPage.vue
  Web/src/pages/post/PostViewPage.vue
  Web/src/router/index.ts
Labels: feature

#29 글 종류에 따른 피드 아이템의 비주얼 표시
  Web/src/components/feed/FeedItem.vue
  Web/src/pages/feed/MainFeedPage.vue
Labels: feature, quick

#30 로그인 폼 ID 규칙 수정
  Web/src/components/app/AppNonLoginAccountMenu.vue
Labels: quick

#31 Decorate README.md using the project and team names with a humble logo
  Doc/imgs/logo_info.txt
  Doc/imgs/pool-logos.jpeg
  Doc/imgs/pool-logos_120x120.png
  Doc/imgs/pool-logos_240x240.png
  Doc/imgs/pool-logos_480x480.png
  Doc/imgs/pool-logos_black.png
  Doc/imgs/pool-logos_transparent.png
  Doc/imgs/pool-logos_white.png
  README.md
Labels: documentation, quick

#32 프론트엔드: 초기 백엔드 연동
  Web/.env.local.example
  Web/package.json
  Web/src/App.vue
  Web/src/components/feed/FeedCompose.vue
  Web/src/components/feed/FeedItem.vue
  Web/src/components/post/CommentsButton.vue
  Web/src/components/post/LikeButton.vue
  Web/src/interfaces/IDatabaseData.ts
  Web/src/pages/account/MyPage.vue
  Web/src/pages/feed/DiscoverPage.vue
  Web/src/pages/feed/MainFeedPage.vue
  Web/src/pages/post/PostViewPage.vue
  Web/src/util/BackendHelper.ts
  Web/yarn.lock
Labels: feature

#33 AI 백앤드 서버 구현
  ai-backend/.gitignore
  ai-backend/README.md
  ai-backend/api_server.py
  ai-backend/cv_summarizer.py
  ai-backend/data/data.md
  ai-backend/kobart_summary/kobart_summary.md
  ai-backend/requirements.txt
Labels: feature
